name: CitybuildSystem
author: TrexFlexx
version: 1.4.1
main: de.trexflexx.main.Main
api-version: 1.16

commands:
  bc:
  belohnung:
  cc:
  ci:
  craft:
  day:
  ec:
  fly:
  globalmute:
  gm:
  heal:
  invsee:
  kopf:
  msg:
  night:
  repair:
  tpo:
  tpohere:
  v:
  vanish:
  ConfigReload:
  Live:
  hat:
  sign:
  speed:
  setspawn:
  spawn:
  enchant:
  tc:
  teamchat:
  kick:
  money:
  eco:
  pay:
  i:
  bank:
  home:
  sethome:
  delhome:
  playtime:
  tpa:
  tpaccept:
  tpdeny:
  ban:
  unban:
  unmute:
  perks:
  say:
  r:
  status:
  profile:
  ptime:
  socialspy:
